// <auto-generated />
namespace Systemet.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class lagttillplatsvidevenmang : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(lagttillplatsvidevenmang));
        
        string IMigrationMetadata.Id
        {
            get { return "201705181548045_lagt till plats vid evenmang"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
